version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # depends_on:
    #   - nodejs
    # networks:
    #   - ms-inventory-networks

  # ngrok:
  #   image: ngrok/ngrok:latest
  #   restart: unless-stopped
  #   command:
  #     - "start"
  #     - "--all"
  #     - "--config"
  #     - "/etc/ngrok.yml"
  #   volumes:
  #     - ./ngrok.yml:/etc/ngrok.yml
  #   ports:
  #     - 4040:4040

  # nodejs:
  #   build: .
  #   container_name: ms-inventory-nodejs
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./data:/app/data
  #   networks:
  #     - ms-inventory-networks
# networks:
#   ms-inventory-networks:
#     driver: bridge
