"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const validate_middleware_1 = require("../../middlewares/validate.middleware");
const auth_middleware_1 = require("../../middlewares/auth.middleware");
const location_controller_1 = require("../../controllers/location.controller");
const location_schema_1 = require("../../schemas/location.schema");
const router = (0, express_1.Router)();
router.get('/', [auth_middleware_1.verifyToken, auth_middleware_1.isUserActive], location_controller_1.findAllLocationController);
router.post('/', [auth_middleware_1.verifyToken, auth_middleware_1.isUserActive, auth_middleware_1.isRoleAdmin, (0, validate_middleware_1.validate)(location_schema_1.locationSchema.create)], location_controller_1.createLocationController);
router.put('/:id', [auth_middleware_1.verifyToken, auth_middleware_1.isUserActive, auth_middleware_1.isRoleAdmin, (0, validate_middleware_1.validate)(location_schema_1.locationSchema.update)], location_controller_1.updateLocationController);
router.delete('/:id', [auth_middleware_1.verifyToken, auth_middleware_1.isUserActive, auth_middleware_1.isRoleAdmin, (0, validate_middleware_1.validate)(location_schema_1.locationSchema.delete)], location_controller_1.deleteLocationController);
exports.default = router;
